pract 5 :- Implement bootstrapping sampling technique on the given dataset.

In [8]:
import numpy as np

In [9]:
d = np.array([10,20,30,40,50,60,70,80,90,100])

In [25]:
num_bootstrap_samples = 10

In [26]:
for i in range(num_bootstrap_samples):
    # Generate a bootstrap sample with replacement
    bootstrap_sample = np.random.choice(d, size=5, replace=True)
    print(bootstrap_sample)
    

[20 30 50 80 80]
[100  10 100  80  60]
[90 20 30 10 80]
[90 40 70 30 40]
[ 50  40  20  70 100]
[90 90 20 10 50]
[20 30 70 20 50]
[20 30 70 30 40]
[20 80 60 20 20]
[100  70  70  40  80]
